version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  ml:
    build: ./ml
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
