"""fresh_initial

Revision ID: 650e77e17d4c
Revises: 3e212fbd2ff0
Create Date: 2026-04-09 20:49:22.293712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "650e77e17d4c"
down_revision: Union[str, None] = "3e212fbd2ff0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
